language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2"
sudo: required
services:
  - docker
notifications:
  email:
    - ricomroatfauchard08@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
    - main
env:
  global:
  # Remove for conciseness
before_install:
  - gem install travis -v 1.8.5 --no-rdoc --no-ri
  - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
  - sudo chmod +x /usr/local/bin/ecs-cli
  - export BUILD_NAME=balita1124-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
  - export CONTAINER_IP=52.53.169.60
  - export PLATFORM_TEST_NAME="balita1124-platform-tests"
script:
  - sh travis_scripts/tag_build.sh
#  - sh travis_scripts/build_services.sh
#  - sh travis_scripts/deploy_to_docker_hub.sh
#  - sh travis_scripts/deploy_amazon_ecs.sh
#  - sh travis_scripts/trigger_platform_tests.sh